using System;
using System.Threading.Tasks;
using Unity.Netcode;
using Unity.Netcode.Transports.UTP;
using Unity.Services.Authentication;
using Unity.Services.Core;
using Unity.Services.Relay;
using Unity.Services.Relay.Models;
using UnityEngine;

/// <summary>
/// Handles Unity Services bootstrap plus Relay-backed Netcode for GameObjects startup.
/// Attach this component to a scene object alongside a UnityTransport and
/// call the public methods to host or join a game.
/// </summary>
public class RelayNetworkManager : MonoBehaviour
{
    [Header("Relay settings")]
    [SerializeField]
    private int maxConnections = 10;

    [SerializeField]
    private UnityTransport transport;

    /// <summary>
    /// Latest generated join code when hosting via Relay.
    /// </summary>
    public string LastJoinCode { get; private set; }

    private Task initializationTask;

    private void Awake()
    {
        // Kick off service initialization early so UI can call into this manager quickly.
        initializationTask = InitializeServicesAsync();
    }

    /// <summary>
    /// Starts hosting using Unity Relay and configures NGO to use the allocated server.
    /// </summary>
    public async Task<string> StartRelayHostAsync()
    {
        await EnsureInitialized();
        EnsureTransport();

        try
        {
            var allocation = await RelayService.Instance.CreateAllocationAsync(maxConnections);
            LastJoinCode = await RelayService.Instance.GetJoinCodeAsync(allocation.AllocationId);

            var relayServerData = new RelayServerData(allocation, "dtls");
            transport.SetRelayServerData(relayServerData);

            if (!NetworkManager.Singleton.StartHost())
            {
                throw new InvalidOperationException("NetworkManager failed to start host.");
            }

            Debug.Log($"Relay host started. Join code: {LastJoinCode}");
            return LastJoinCode;
        }
        catch (Exception ex)
        {
            Debug.LogError($"Failed to start Relay host: {ex}");
            throw;
        }
    }

    /// <summary>
    /// Connects a client to a Relay allocation using the provided join code.
    /// </summary>
    /// <param name="joinCode">Join code generated by the host.</param>
    public async Task StartRelayClientAsync(string joinCode)
    {
        if (string.IsNullOrWhiteSpace(joinCode))
        {
            throw new ArgumentException("Join code must not be empty.", nameof(joinCode));
        }

        await EnsureInitialized();
        EnsureTransport();

        try
        {
            var joinAllocation = await RelayService.Instance.JoinAllocationAsync(joinCode.Trim());
            var relayServerData = new RelayServerData(joinAllocation, "dtls");
            transport.SetRelayServerData(relayServerData);

            if (!NetworkManager.Singleton.StartClient())
            {
                throw new InvalidOperationException("NetworkManager failed to start client.");
            }

            Debug.Log("Relay client started and connecting...");
        }
        catch (Exception ex)
        {
            Debug.LogError($"Failed to start Relay client: {ex}");
            throw;
        }
    }

    private async Task InitializeServicesAsync()
    {
        try
        {
            Debug.Log("Initializing Unity Services for Relay...");
            await UnityServices.InitializeAsync();

            if (!AuthenticationService.Instance.IsSignedIn)
            {
                await AuthenticationService.Instance.SignInAnonymouslyAsync();
            }

            Debug.Log("Unity Services initialized and user signed in.");
        }
        catch (Exception ex)
        {
            Debug.LogError($"Unity Services initialization failed: {ex}");
            throw;
        }
    }

    private async Task EnsureInitialized()
    {
        if (initializationTask == null)
        {
            initializationTask = InitializeServicesAsync();
        }

        await initializationTask;
    }

    private void EnsureTransport()
    {
        if (transport == null)
        {
            transport = FindObjectOfType<UnityTransport>();
        }

        if (transport == null)
        {
            throw new InvalidOperationException("UnityTransport component is missing. Attach one to the scene.");
        }
    }
}
